# Generated by Django 4.1.7 on 2023-04-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_report_author_alter_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='correlatons_range',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
