# Generated by Django 4.0.5 on 2023-05-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_feedback_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='firs_tname',
            new_name='first_name',
        ),
    ]
