# Generated by Django 4.0.5 on 2023-05-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_article_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
    ]
