# Generated by Django 4.1.7 on 2023-06-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_article_moderated"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryFle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="excel_files/")),
            ],
        ),
    ]
