# Generated by Django 4.1.7 on 2023-06-07 16:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_temporaryfle"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TemporaryFle",
            new_name="TemporaryFile",
        ),
    ]
